### ISSUE TITLE
USB Ethernet on Intel NUC?

### ISSUE THREAD

**Issue by vinhdizzo** [HarmlessSaucer/home-assistant-config#2]
Hi!

Apologies for messaging you via this avenue. I too have a red Intel NUC and would like to use a USB Ethernet adapter with Home Assistant.  I ran into [your](https://community.home-assistant.io/t/my-steps-to-success-for-hass-io-on-intel-nuc/43915/17) post asking it, but don't see anyone responding to your question.  I was wondering if you figured out how to get it to work?  I've tried 3 USB ethernet adapters but no luck.  Two of them claim to work on Linux.

Thank you in advance for any guidance you might have.

**Comment by HarmlessSaucer** [comment]
Sadly no... I gave up after trying 2 or 3 seperate adapters.
I haven't tried with any recent versions of Home-Assistant.
I'd recommend maybe going a different route - Maybe use Ubuntu as your base OS or, install Proxmox and then run it as a VM.  Both of those should find the USB ethernet adaptors okay.

**Comment by vinhdizzo** [comment]
Thanks for confirming. I also posted on the HA forums and have not received a response.

I did go the route that you have suggested: set up Ubuntu 20.04 as the base OS with Docker and Portainer, and installed HA via Docker.
